[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "iflow-mcp_mcp-server-obsidian-omnisearch"
version = "0.1.0"
description = "MCP server for Obsidian Omnisearch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.25.0",
    "pydantic>=2.0.0",
]

[project.scripts]
mcp-server-obsidian-omnisearch = "mcp_server_obsidian_omnisearch.server:main"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_server_obsidian_omnisearch"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/README.md",
]